In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [64]:
df = pd.DataFrame({'text':
            ['people watch campusx', 
             'campusx watch campusx', 
             'people write comment', 
             'campusx write comment'], 
                   'output':[1,1,0,0]})

In [65]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [44]:
cv = CountVectorizer()

In [45]:
bow = cv.fit_transform(df['text'])

In [46]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [66]:
vocabulary = sorted(cv.vocabulary_, 
                    key=lambda x: cv.vocabulary_[x])

In [48]:
vocabulary

['campusx', 'comment', 'people', 'watch', 'write']

In [49]:
bow.toarray()

array([[1, 0, 1, 1, 0],
       [2, 0, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [50]:
bow.toarray()[0] # people watch campusx 

array([1, 0, 1, 1, 0])

In [68]:
bow = cv.fit_transform(["""hello mamma ooo you 
                        can\'t tell me you don\'t wanna 
                        go up there for so long you whooooooooo"""])

In [69]:
cv.vocabulary_

{'hello': 4,
 'mamma': 6,
 'ooo': 8,
 'you': 15,
 'can': 0,
 'tell': 10,
 'me': 7,
 'don': 1,
 'wanna': 13,
 'go': 3,
 'up': 12,
 'there': 11,
 'for': 2,
 'so': 9,
 'long': 5,
 'whooooooooo': 14}

In [70]:
cv.transform(["""you mama what up hommie my 
                man for real yoo what up oooo you 
              can tel me don wanna for so logn wuhoooooooo"""]).toarray()

array([[1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1]])

In [54]:
cv = CountVectorizer(binary=True)

In [71]:
bow = cv.fit_transform(["""playful joyful enjoy cry noise work 
                        dedication"""])

In [58]:
bow.toarray()

array([[1, 1, 1, 1, 1, 1, 1]])

### max-features hyperparamer is considered across the corpus. 
### That is, only the most occurring item is considered, 
### rest of the elements in the sentence are ignored.